AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  deploy the serverless microservice:
    lambda's: authentication, authorization
    stepfunction's:

Parameters:
  ParameterInstancePrefix:
    Type: String
    Default: "shavika"
    Description: "Prefix to be used in names of the things created by this stack."
  TagProvisioner:
    Type: String
    Default: "SAM"
    Description: "Tag-Provisioner"
  TagProject:
    Type: String
    Default: "DOMS"
    Description: "Tag-Project"
  TagBusinessUnit:
    Type: String
    Default: "Platform"
    Description: "Tag-BusinessUnit"
  TagBusinessModel:
    Type: String
    Default: "shared"
    Description: "Tag-BusinessModel"
  TagProductVersion:
    Type: String
    Default: "2023.1.0.0"
    Description: "Tag-ProductVersion"
  StackName:
    Type: String
    Default: "shavika-service"
    Description: "Tag-ProductVersion"

  DataSourceName:
    Type: String
    Default: "doms"
    Description: "DynamoDB user management table with all tenant base"

Resources:

  DataSourceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./stack-datasource.yaml
      Parameters:
        StackName: !Ref StackName
        DataSourceName: !Ref DataSourceName
      Tags:
        - Key: Name
          Value: DataSourceStack

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./stack-lambda.yaml
      Parameters:
        StackName: !Ref StackName
        DataSourceName: !Ref DataSourceName
      Tags:
        - Key: Name
          Value: LambdaStack

  ApiGatewayStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - LambdaStack
    Properties:
      TemplateURL: ./stack-api-gateway.yaml
      Parameters:
        AuthenticationFunctionArn: !GetAtt LambdaStack.Outputs.AuthenticationFunctionArn
        AuthorizationFunctionArn: !GetAtt LambdaStack.Outputs.AuthorizationFunctionArn
        PlatformFunctionArn: !GetAtt LambdaStack.Outputs.PlatformFunctionArn
      Tags:
        - Key: Name
          Value: ApiGatewayStack


#############################################################################################################################################################
# {output}
# More info about Output:
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html
#############################################################################################################################################################
Outputs:
  AuthenticationFunctionArn:
    Description: "Authentication Lambda funcation ARN value"
    Value:
      Fn::GetAtt: LambdaStack.Outputs.AuthenticationFunctionArn
  AuthorizationFunctionArn:
    Description: "Authorization Lambda funcation ARN value"
    Value:
      Fn::GetAtt: LambdaStack.Outputs.AuthorizationFunctionArn
  PlatformFunctionArn:
    Description: "Platform Lambda funcation ARN value"
    Value:
      Fn::GetAtt: LambdaStack.Outputs.PlatformFunctionArn

  DataSourceDynamoDBTableArn:
    Description: "DynamoDB table for serverless microserive architecture for DOMS product (Data Object Modeling)"
    Value:
      Fn::GetAtt: DataSourceStack.Outputs.DataSourceDynamoDBTableArn

  RestApiEndPoint:
    Description: "Application end point to access form public"
    Value:
      Fn::GetAtt: ApiGatewayStack.Outputs.RestApiEndPoint
