version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "shavika-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-zo171pekesrf"
s3_prefix = "shavika"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "ParameterInstancePrefix=\"shavika\" TagProvisioner=\"SAM\" TagProject=\"DOMS\" TagBusinessUnit=\"platform\" TagBusinessModel=\"shared\" TagProductVersion=\"2023.1.0.0\""
image_repositories = []
disable_rollback = false