#############################################################################################################################################################
# {Rest api-gatway}             
# More info about Function Resource: 
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-restapi.html                        
#############################################################################################################################################################
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  deploy the serverless microservice: discovery register - api mesh:

Parameters:
  StackName:
    Type: String
    Default: "shavika-service"
    Description: "this is api gatway prefix name"
  ApiGatewayStageName:
    Default: v1
    Description : Stage name for the API Gateway
    Type: String  
  AuthenticationFunctionArn:
    Type: String  
    Description : Arn Id for Authentication Lambda Function
  AuthorizationFunctionArn:
    Type: String  
    Description : Arn Id for Authorization Lambda Function
  AdminFunctionArn:
    Type: String  
    Description : Arn Id for Repository write Lambda Function

Resources:
  #
  #
  # <<<<<<< rest-api-gateway >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  restApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      EndpointConfiguration:
        Types:
          - REGIONAL
      Description: An API Gateway with a Lambda Integration
      Name: !Sub "${StackName}-discover-registry"
  # <<<<<<< deployment of rest-api >>>>>>>>>>>
  apiDeployment: 
    Type: AWS::ApiGateway::Deployment
    DependsOn: 
      - authMethod
      - repoWriteMethod
      - repoReadMethod
      - swaggerMethod
    Properties:
      Description: Deploy the auth rest api
      RestApiId: !Ref restApiGateway
  # <<<<<<< stageing of rest-api {v1} >>>>>>>>>>>
  apiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref apiDeployment
      Description: staging the auth rest api
      RestApiId: !Ref restApiGateway
      StageName: !Ref ApiGatewayStageName

  #
  #
  # <<<<<<< Lambda Token Authorizer >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  AuthorizersLambdaToken:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: LambdaAuthorizerToken
      Type: TOKEN
      AuthorizerResultTtlInSeconds: '0'
      RestApiId: !Ref restApiGateway
      IdentitySource: method.request.header.Authorization
      AuthorizerUri: !Sub
        - 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations'
        - lambdaArn: !Ref AuthorizationFunctionArn

  # <<<<<<< authorization lambda API-execution-permissions for rest-api >>>>>>>>>>>
  tokenAuthzLambdaApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref AuthorizationFunctionArn
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${restApiGateway}/authorizers/${AuthorizersLambdaToken}

  # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # <<<<<<< RESOURCE PATH "/api/auth/" >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

  # <<<<<<< resource => /api >>>>>>>>>>>
  apiResource:  
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt restApiGateway.RootResourceId
      PathPart: 'api'
      RestApiId: !Ref restApiGateway

  # <<<<<<< resource => /api/auth >>>>>>>>>>>
  authResource:  
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref apiResource
      PathPart: 'auth'
      RestApiId: !Ref restApiGateway

  # <<<<<<< resource => /api/auth/{proxy+} >>>>>>>>>>>
  authProxyResource:  
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref authResource
      PathPart: '{proxy+}'
      RestApiId: !Ref restApiGateway

  # <<<<<<< resource => /api/auth/{proxy+} | method {ANY} |  lambda-proxy-integration >>>>>>>>>>>
  authMethod:  
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: ANY
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub
          - 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations'
          - lambdaArn: !Ref AuthenticationFunctionArn
        PassthroughBehavior: WHEN_NO_MATCH
        TimeoutInMillis: 29000  
      OperationName: 'auth lambda function'
      ResourceId: !Ref authProxyResource
      RestApiId: !Ref restApiGateway

  # <<<<<<< Auth lambda API-execution-permissions for rest-api >>>>>>>>>>>
  authLambdaApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref AuthenticationFunctionArn
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${restApiGateway}/${ApiGatewayStageName}/ANY/api/auth/{proxy+}

  # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # <<<<<<< RESOURCE PATH "/api/admin/" >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

  # <<<<<<< resource => /api/admin >>>>>>>>>>>
  adminResource:  
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref apiResource
      PathPart: 'admin'
      RestApiId: !Ref restApiGateway

  # <<<<<<< resource => /api/admin/{proxy+} >>>>>>>>>>>
  adminProxyResource:  
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref adminResource
      PathPart: '{proxy+}'
      RestApiId: !Ref restApiGateway

  # <<<<<<< resource => /api/admin/{proxy+} | method {ANY} |  lambda-proxy-integration >>>>>>>>>>>
  adminMethod:  
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref AuthorizersLambdaToken
      HttpMethod: ANY
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub
          - 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations'
          - lambdaArn: !Ref AdminFunctionArn
        PassthroughBehavior: WHEN_NO_MATCH
        TimeoutInMillis: 29000  
      OperationName: 'Database repositort operation with lambda function'
      ResourceId: !Ref adminProxyResource
      RestApiId: !Ref restApiGateway
  # <<<<<<< repository lambda API-execution-permissions for rest-api >>>>>>>>>>>
  repoWriteLambdaApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref AdminFunctionArn
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${restApiGateway}/${ApiGatewayStageName}/ANY/api/admin/{proxy+}


  # <<<<<<< resource {/api/admin/swagger} >>>>>>>>>>>
  adminSwaggerResource:  
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref adminResource
      PathPart: 'swagger'
      RestApiId: !Ref restApiGateway

  # <<<<<<< resource => /api/admin/swagger | method {ANY} |  lambda-proxy-integration >>>>>>>>>>>
  adminSwaggerMethod:  
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: ANY
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub
          - 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations'
          - lambdaArn: !Ref AdminFunctionArn
        PassthroughBehavior: WHEN_NO_MATCH
        TimeoutInMillis: 29000  
      OperationName: 'auth lambda function'
      ResourceId: !Ref adminSwaggerResource
      RestApiId: !Ref restApiGateway
  # <<<<<<< admin swagger lambda API-execution-permissions for rest-api >>>>>>>>>>>
  adminSwaggerLambdaApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref AdminFunctionArn
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${restApiGateway}/${ApiGatewayStageName}/ANY/api/admin/swagger


#############################################################################################################################################################
# {output}     
# More info about Output: 
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html
#############################################################################################################################################################
Outputs:
  RestApiEndPoint:
    Description: "Application end point to access form public"
    Value: !Sub "https://${restApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${apiStage}/*/*"
    Export:
      Name: RestApiEndPoint