#############################################################################################################################################################
# {dynamodb}
# More info about Function Resource:
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html
#############################################################################################################################################################
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  deploy the serverless microservice: dynamodb for data source:

Parameters:
  StackName:
    Type: String
  DataSourceName:
    Type: String
    Default: "doms"
    Description: "DynamoDB service name for data repository with all tenant base"

Resources:
  # <<<<<<<  {{DYNAMODB}} DynamoDB table for serverless microserive architecture for DOMS product (Data Object Modeling) >>>>>>>>>>>
  DataSourceTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: !Join ["",[!Ref StackName,"-",!Ref DataSourceName]]
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        -
          AttributeName: "PK"
          AttributeType: "S"
        -
          AttributeName: "SK"
          AttributeType: "S"
        -
          AttributeName: "ENTITIES"
          AttributeType: "S"
        -
          AttributeName: "PARENT"
          AttributeType: "S"
        -
          AttributeName: "MAPPINGS"
          AttributeType: "S"
      KeySchema:
        - 
          AttributeName: "PK"
          KeyType: "HASH"
        - 
          AttributeName: "SK"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        -
          IndexName: "ENTITIES_INX"
          KeySchema:
            -
              AttributeName: "ENTITIES"
              KeyType: "HASH"
            -
              AttributeName: "PK"
              KeyType: "RANGE"  
          Projection:
            NonKeyAttributes:
            - SK
            ProjectionType: "INCLUDE"
        -
          IndexName: "PATENT_INX"
          KeySchema:
            -
              AttributeName: "PARENT"
              KeyType: "HASH"
            -
              AttributeName: "SK"
              KeyType: "RANGE"  
          Projection:
            NonKeyAttributes:
            - SK
            ProjectionType: "INCLUDE"
        -
          IndexName: "MAPPINGS_IDX"
          KeySchema:
            -
              AttributeName: "MAPPINGS"
              KeyType: "HASH"
            -
              AttributeName: "PK"
              KeyType: "RANGE"  
          Projection:
            NonKeyAttributes:
            - PK
            ProjectionType: "INCLUDE"

#############################################################################################################################################################
# {output}     
# More info about Output: 
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html
#############################################################################################################################################################
Outputs:
  DataSourceTableArn:
    Value: !GetAtt DataSourceTable.Arn
    Export:
      Name: DataSourceTableArn
  DataSourceTableName:
    Value: !Ref DataSourceTable
    Export:
      Name: DataSourceTableName

