#############################################################################################################################################################
# {Rest api-gatway}             
# More info about Function Resource: 
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-restapi.html                        
#############################################################################################################################################################
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  deploy the serverless microservice: discovery register - api mesh:

Parameters:
  StackName:
    Type: String
    Default: "shavika-service"
    Description: "this is api gatway prefix name"
  ApiGatewayStageName:
    Default: v1
    Description : Stage name for the API Gateway
    Type: String  
  AuthenticationFunctionArn:
    Type: String  
    Description : Arn Id for Authentication Lambda Function
  AuthorizationFunctionArn:
    Type: String  
    Description : Arn Id for Authorization Lambda Function
  RepositoryFunctionArn:
    Type: String  
    Description : Arn Id for Repository write Lambda Function
  QueriesFunctionArn:
    Type: String  
    Description : Arn Id for Query the data Lambda Function

Resources:
  #
  #
  # <<<<<<< rest-api-gateway >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  restApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      EndpointConfiguration:
        Types:
          - REGIONAL
      Description: An API Gateway with a Lambda Integration
      Name: !Sub "${StackName}-discover-registry"
  # <<<<<<< deployment of rest-api >>>>>>>>>>>
  apiDeployment: 
    Type: AWS::ApiGateway::Deployment
    DependsOn: 
      - authMethod
      - repoWriteMethod
      - repoReadMethod
    Properties:
      Description: Deploy the auth rest api
      RestApiId: !Ref restApiGateway
  # <<<<<<< stageing of rest-api {v1} >>>>>>>>>>>
  apiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref apiDeployment
      Description: staging the auth rest api
      RestApiId: !Ref restApiGateway
      StageName: !Ref ApiGatewayStageName

  #
  #
  # <<<<<<< Lambda Token Authorizer >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  AuthorizersLambdaToken:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: LambdaAuthorizerToken
      Type: TOKEN
      AuthorizerResultTtlInSeconds: '0'
      RestApiId: !Ref restApiGateway
      IdentitySource: method.request.header.Authorization
      AuthorizerUri: !Sub
        - 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations'
        - lambdaArn: !Ref AuthorizationFunctionArn

  # <<<<<<< authorization lambda API-execution-permissions for rest-api >>>>>>>>>>>
  tokenAuthzLambdaApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref AuthorizationFunctionArn
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${restApiGateway}/authorizers/${AuthorizersLambdaToken}

  # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # <<<<<<< resource {/auth} >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  authRootResource:  
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt restApiGateway.RootResourceId
      PathPart: 'auth'
      RestApiId: !Ref restApiGateway
  # <<<<<<< resource {/auth/{proxy+}} >>>>>>>>>>>
  authProxyResource:  
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref authRootResource
      PathPart: '{proxy+}'
      RestApiId: !Ref restApiGateway
  # <<<<<<< method {ANY} of {/auth/{proxy+}} lambda-proxy-integration >>>>>>>>>>>
  authMethod:  
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: ANY
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub
          - 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations'
          - lambdaArn: !Ref AuthenticationFunctionArn
        PassthroughBehavior: WHEN_NO_MATCH
        TimeoutInMillis: 29000  
      OperationName: 'auth lambda function'
      ResourceId: !Ref authProxyResource
      RestApiId: !Ref restApiGateway
  # <<<<<<< platform lambda API-execution-permissions for rest-api >>>>>>>>>>>
  authLambdaApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref AuthenticationFunctionArn
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${restApiGateway}/${ApiGatewayStageName}/ANY/auth/{proxy+}

  # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # <<<<<<< resource {/api} >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  repoRootResource:  
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt restApiGateway.RootResourceId
      PathPart: 'api'
      RestApiId: !Ref restApiGateway

  # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # <<<<<<< resource {/api/payload} >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  repoWriteRootResource:  
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref repoRootResource
      PathPart: 'payload'
      RestApiId: !Ref restApiGateway
  # <<<<<<< resource {/api/payload/{proxy+}} >>>>>>>>>>>
  repoWriteProxyResource:  
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref repoWriteRootResource
      PathPart: '{proxy+}'
      RestApiId: !Ref restApiGateway

  # <<<<<<< method {ANY} of {/api/payload/{proxy+}} lambda-proxy-integration >>>>>>>>>>>
  repoWriteMethod:  
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref AuthorizersLambdaToken
      HttpMethod: ANY
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub
          - 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations'
          - lambdaArn: !Ref RepositoryFunctionArn
        PassthroughBehavior: WHEN_NO_MATCH
        TimeoutInMillis: 29000  
      OperationName: 'Repo write lambda function'
      ResourceId: !Ref repoWriteProxyResource
      RestApiId: !Ref restApiGateway
  # <<<<<<< repository lambda API-execution-permissions for rest-api >>>>>>>>>>>
  repoWriteLambdaApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref RepositoryFunctionArn
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${restApiGateway}/${ApiGatewayStageName}/ANY/api/payload/{proxy+}

  # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # <<<<<<< resource {/api/query} >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  repoReadRootResource:  
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref repoRootResource
      PathPart: 'query'
      RestApiId: !Ref restApiGateway
  # <<<<<<< resource {/api/query/{proxy+}} >>>>>>>>>>>
  repoReadProxyResource:  
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref repoReadRootResource
      PathPart: '{proxy+}'
      RestApiId: !Ref restApiGateway

  # <<<<<<< method {ANY} of {/api/query/{proxy+}} lambda-proxy-integration >>>>>>>>>>>
  repoReadMethod:  
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref AuthorizersLambdaToken
      HttpMethod: ANY
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub
          - 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations'
          - lambdaArn: !Ref QueriesFunctionArn
        PassthroughBehavior: WHEN_NO_MATCH
        TimeoutInMillis: 29000  
      OperationName: 'Repo write lambda function'
      ResourceId: !Ref repoReadProxyResource
      RestApiId: !Ref restApiGateway
  # <<<<<<< read lambda API-execution-permissions for rest-api >>>>>>>>>>>
  repoReadLambdaApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref QueriesFunctionArn
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${restApiGateway}/${ApiGatewayStageName}/ANY/api/query/{proxy+}

#############################################################################################################################################################
# {output}     
# More info about Output: 
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html
#############################################################################################################################################################
Outputs:
  RestApiEndPoint:
    Description: "Application end point to access form public"
    Value: !Sub "https://${restApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${apiStage}/*/*"
    Export:
      Name: RestApiEndPoint
