#############################################################################################################################################################
# {AWS SAM template}
# More info about Function Resource:
# https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
#############################################################################################################################################################
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  deploy the serverless microservice:
    lambda's: authentication, authorization
    stepfunction's:

Parameters:
  ParameterInstancePrefix:
    Type: String
    Default: "shavika"
    Description: "Prefix to be used in names of the things created by this stack."
  TagProvisioner:
    Type: String
    Default: "SAM"
    Description: "Tag-Provisioner"
  TagProject:
    Type: String
    Default: "DOMS"
    Description: "Tag-Project"
  TagBusinessUnit:
    Type: String
    Default: "Platform"
    Description: "Tag-BusinessUnit"
  TagBusinessModel:
    Type: String
    Default: "shared"
    Description: "Tag-BusinessModel"
  TagProductVersion:
    Type: String
    Default: "2023.1.0.0"
    Description: "Tag-ProductVersion"
  StackName:
    Type: String
    Default: "shavika-service"
    Description: "Tag-ProductVersion"

Resources:

  # ********************** S3 Stack ****************** #
  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: stack-s3.yaml
      Parameters:
        StackName: !Ref StackName
      Tags:
        - Key: Name
          Value: S3Stack

