#############################################################################################################################################################
# {AWS SAM template}
# More info about Function Resource:
# https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
#############################################################################################################################################################
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  deploy the serverless microservice:
    lambda's: authentication, authorization
    stepfunction's:

Parameters:
  StackName:
    Type: String
    Default: "shavika-doms-backend"
  ParameterInstancePrefix:
    Type: String
    Default: "shavika-doms-backend"
  TagProvisioner:
    Type: String
    Default: "SAM"
  TagProject:
    Type: String
    Default: "DOMS"
  TagBusinessUnit:
    Type: String
    Default: "Platform"
  TagBusinessModel:
    Type: String
    Default: "shared"
  TagProductVersion:
    Type: String
    Default: "1.0.0"

Resources:

  # ********************** S3 Stack ****************** #
  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: stack-s3.yaml
      Parameters:
        StackName: !Ref StackName
      Tags:
        - Key: Name
          Value: S3Stack

  # ********************** DynamoDB Stack ****************** #
  DataSourceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: stack-datasource.yaml
      Parameters:
        StackName: !Ref StackName
      Tags:
        - Key: Name
          Value: DataSourceStack

  # ********************** Lambda Stack ****************** #
  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: stack-lambda.yaml
      Parameters:
        StackName: !Ref StackName
        DomsRepoBucketName: !GetAtt S3Stack.Outputs.DomsRepoBucketName
        DataSourceTableName: !GetAtt DataSourceStack.Outputs.DataSourceTableName
      Tags:
        - Key: Name
          Value: LambdaStack

  # ********************** ApiGatway Stack ****************** #
  ApiGatewayStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - LambdaStack
    Properties:
      TemplateURL: stack-api-gateway.yaml
      Parameters:
        StackName: !Ref StackName
        AuthenticationFunctionArn: !GetAtt LambdaStack.Outputs.AuthenticationFunctionArn
        AuthorizationFunctionArn: !GetAtt LambdaStack.Outputs.AuthorizationFunctionArn
        RepositoryFunctionArn: !GetAtt LambdaStack.Outputs.RepositoryFunctionArn
      Tags:
        - Key: Name
          Value: ApiGatewayStack


#############################################################################################################################################################
# {output}
# More info about Output:
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html
#############################################################################################################################################################
Outputs:
  AuthenticationFunctionArn:
    Description: "Authentication Lambda funcation ARN value"
    Value:
      Fn::GetAtt: LambdaStack.Outputs.AuthenticationFunctionArn
  AuthorizationFunctionArn:
    Description: "Authorization Lambda funcation ARN value"
    Value:
      Fn::GetAtt: LambdaStack.Outputs.AuthorizationFunctionArn
  RepositoryFunctionArn:
    Description: "Repository Lambda funcation ARN value"
    Value:
      Fn::GetAtt: LambdaStack.Outputs.RepositoryFunctionArn

  DataSourceTableArn:
    Description: "DynamoDB table for serverless microserive architecture for DOMS product (Data Object Modeling)"
    Value:
      Fn::GetAtt: DataSourceStack.Outputs.DataSourceTableArn

  RestApiEndPoint:
    Description: "Application end point to access form public"
    Value:
      Fn::GetAtt: ApiGatewayStack.Outputs.RestApiEndPoint
