# This workflow runs only for PRs raised by dependabot.
# The reason why this needs to be a standalone workflow is because GitHub prohibits dependabot PRs to access GitHub secrets.
# Since our CI workflow deals with GitHub secrets for image push to ECR, we cannot have dependabot workflow inside CI workflow.

name: Dependabot PR auto merge workflow

on:
  workflow_dispatch:
    inputs:
      # working-directory is added to accommodate monorepo.  For multi repo, defaults to '.', current directory
      working-directory:
        required: false
        type: string
        default: '.'
      sam-version:
        required: false
        type: string
        default: '1.71.0'
      sam-template:
        required: false
        type: string
        default: 'template.yaml'

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    # accommodating monorepo, this sets the working directory at the job level, for multi repo, defaults to "."
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    # env variables have to be defined after "environment", so github actions knows where to retrieve the secrets
    env:
      SAM_TEMPLATE: ${{ inputs.sam-template }}

    # run this workflow only for dependabot
    if: ${{ github.actor == 'dependabot[bot]'}}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          #role-to-assume: ${{ secrets.ROLE_TO_ASSUME }} # TODO: enable once switch into IAM role base access

      - name: Setup SAM
        uses: aws-actions/setup-sam@v2
        with:
          version: ${{ inputs.sam-version }}
          use-installer: true #recommended approach, does not require Python to be installed, and is faster than the default installation method.

      - name: Print debug info
        run: |
          echo working_directory is ${{ inputs.working-directory }}
          echo SAM version is ${{ inputs.sam-version }}
          echo sam-template is ${{ inputs.sam-template }}

      # Build inside Docker containers
      - name: Build resources
        run: sam build --template ${SAM_TEMPLATE} --use-container

  automerge:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    # run this workflow only for dependabot
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            nodejs.org:443

      - uses: fastify/github-action-merge-dependabot@v3
        with:
          # it is an automatically generated secret that lets you make authenticated calls to the GitHub APIs.
          github-token: ${{ secrets.GITHUB_TOKEN }}
